url: https://wenqiangjin.github.io/

title: 物联网感知安全实验室

keywords: 物联网感知安全实验室

description: 物联网感知安全实验室

address: 湖南长沙岳麓区麓山南路116号 湖南大学信息科学与工程学院

contacts: 靳文强教授

email: wqjin@hnu.edu.cn

exclude:
  - README.md
